spring:
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update

    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.springframework.web: DEBUG

server:
  port: 9090
